---
# Source: swaggereditor-dashboard/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: swaggereditor-dashboard
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"apieditor"}}'
  labels:
    "app.kubernetes.io/name": swaggereditor-dashboard
    "helm.sh/chart": swaggereditor-dashboard-1.0.0
    "app.kubernetes.io/instance": swaggereditor
    "app.kubernetes.io/component": swaggereditor-dashboard-serviceAccount
---
# Source: swaggereditor-dashboard/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: swaggereditor-dashboard-agent
  labels:
    "app.kubernetes.io/name": swaggereditor-dashboard
    "helm.sh/chart": swaggereditor-dashboard-1.0.0
    "app.kubernetes.io/instance": swaggereditor
    "app.kubernetes.io/component": swaggereditor-dashboard-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
---
# Source: swaggereditor-dashboard/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: swaggereditor-dashboard-agent
  labels:
    "app.kubernetes.io/name": swaggereditor-dashboard
    "helm.sh/chart": swaggereditor-dashboard-1.0.0
    "app.kubernetes.io/instance": swaggereditor
    "app.kubernetes.io/component": swaggereditor-dashboard-roleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: swaggereditor-dashboard-agent
subjects:
  - kind: ServiceAccount
    name: swaggereditor-dashboard
    namespace: tools
---
# Source: swaggereditor-dashboard/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: swaggereditor-swaggereditor-dashboard
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: apieditor-tls
  labels:
    app: swaggereditor-dashboard
    chart: swaggereditor-dashboard-1.0.0
    release: swaggereditor
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: proxy
  selector:
    app: swaggereditor-dashboard
    release: swaggereditor
---
# Source: swaggereditor-dashboard/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaggereditor-swaggereditor-dashboard
  labels:
    app: swaggereditor-dashboard
    chart: swaggereditor-dashboard-1.0.0
    release: swaggereditor
    heritage: Helm
    "app.kubernetes.io/name": swaggereditor-swaggereditor-dashboard
    "helm.sh/chart": swaggereditor-dashboard-1.0.0
    "app.kubernetes.io/instance": swaggereditor
    "app.kubernetes.io/component": swaggereditor-swaggereditor-dashboard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swaggereditor-dashboard
      release: swaggereditor
  template:
    metadata:
      labels:
        app: swaggereditor-dashboard
        release: swaggereditor
        "app.kubernetes.io/name": swaggereditor-dashboard
        "helm.sh/chart": swaggereditor-dashboard-1.0.0
        "app.kubernetes.io/instance": swaggereditor-dashboard
        "app.kubernetes.io/component": swaggereditor-dashboard-pod
    spec:
      serviceAccountName: swaggereditor-dashboard
      volumes:
        - name: proxy-tls
          secret:
            secretName: apieditor-tls
      containers:
        - name: oauth-proxy
          image: openshift/oauth-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: public
          args:
            - --https-address=:8443
            - --provider=openshift
            - --openshift-service-account=swaggereditor-dashboard
            - --upstream=http://localhost:3000
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --cookie-secret=SECRET
          volumeMounts:
            - mountPath: /etc/tls/private
              name: proxy-tls
        - name: swaggereditor-dashboard
          image: "docker.io/swaggerapi/swagger-editor:v3.8.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          envFrom:
            - configMapRef:
                name: "ibmcloud-config"
                optional: true
          resources:
            {}
---
# Source: swaggereditor-dashboard/templates/route.yaml
apiVersion: v1
kind: Route
metadata:
  name: apieditor
spec:
  to:
    kind: Service
    name: swaggereditor-swaggereditor-dashboard
  tls:
    termination: Reencrypt
