commonLabels:
 app: "sonarqube"
resources:
 - base.yaml
patchesJson6902:
 - path: patch-deployment.yaml
   target:
     group: extensions
     version: v1beta1
     kind: Deployment
     name: sonarqube-sonarqube
#
# - path: patch-test.yaml
#   target:
#     group: ""
#     version: v1
#     kind: Pod
#     name: jenkins-ui-test-f7vdc

