---
# Source: tool-config/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-access
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/version: 0.1.2
    app.kubernetes.io/part-of: garage-cloud-native-toolkit
    app.kubernetes.io/component: tools
    chart: tool-config-0.1.2
    release: argocd-config
    group: catalyst-tools
    grouping: garage-cloud-native-toolkit
  annotations:
    description: Secret to hold the username and password for argocd so that other components can access it
type: Opaque
stringData:
  ARGOCD_PASSWORD: "argocd-server-54669c7886-pj76n"
  ARGOCD_USER: "admin"
---
# Source: tool-config/templates/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-config
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/version: 0.1.2
    app.kubernetes.io/part-of: garage-cloud-native-toolkit
    app.kubernetes.io/component: tools
    chart: tool-config-0.1.2
    release: argocd-config
    group: catalyst-tools
    grouping: garage-cloud-native-toolkit
  annotations:
    description: Config map to hold the url for argocd in the environment so that other components can access it
data:
  ARGOCD_URL: ""
