---
# Source: solsa-cm/templates/solsa-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: solsa-cm
  labels:
    "app.kubernetes.io/name": "argocd"
    "app.kubernetes.io/instance": "argocd"
    group: "catalyst-tools"
data:
  solsa.yaml: |
    clusters:
    - name: 'in-cluster'
      ingress:
        iks:
          subdomain: "garage-dev-ocp3-c-460849-0143c5dd31acd8e030a1d6e0ab1380e3-0000.us-east.containers.appdomain.cloud"
          tlssecret: ""
    contexts:
    - name: 'in-cluster-context'
      cluster: 'in-cluster'
