{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
    name: pactbroker-config
    labels:
        app: {{ include "pact-broker.name" . }}
        group: {{ .Values.group }}
data:
    PACTBROKER_URL: {{ include "pact-broker.url" . }}
{{- end -}}